apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: krishkumarshrestha/client
        name: client
        ports:
        - containerPort: 3000
          name: client
