apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mongo
        name: db
        ports:
        - containerPort: 27017
          name: db
