apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: krishkumarshrestha/server
        name: server
        ports:
        - containerPort: 4000
          name: server
        env:
        - name: CLIENT_URL
          value: http://54.164.91.163:3000
        - name: MONGODB_URI
          value: mongodb://db-svc:27017/db_socialecho
        - name: PORT
          value: "4000"
